server:
  port: 8081

spring:
  application:
    name: SWIGGY-APP

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

url:
 restaurant-service: http://RESTAURANT-SERVICE/restaurant/orders/status/